language: node_js

node_js:
  - 10.4.1

os:
  - linux
  - osx

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run test
  - npm run lint
  - npm run build
